services:
  configurator:
    image: alpine:latest
    container_name: configurator
    volumes:
      - ./config.yaml:/config.yaml
      - ./.sh:/.sh
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      CONFIG_FILE: /config.yaml
    command: >
      /bin/sh -c "
      echo 'http://dl-cdn.alpinelinux.org/alpine/v3.20/main' > /etc/apk/repositories &&
      echo 'http://dl-cdn.alpinelinux.org/alpine/v3.20/community' >> /etc/apk/repositories &&
      apk update &&
      apk add --no-cache jq yq docker-cli docker-compose &&
      chmod +x /.sh &&
      /.sh &&
      docker-compose -f /generated/docker-compose.yaml up
      "
